<a href="https://colab.research.google.com/github/alpharmike/pytorch-hands-on/blob/main/00_pytorch_fundamentals_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [ ]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [ ]:
# Import torch
import torch


# Create random tensor
random_tensor_A = torch.rand(7, 7)
random_tensor_A

tensor([[0.5760, 0.0313, 0.5887, 0.5468, 0.5932, 0.5722, 0.7712],
        [0.6455, 0.2797, 0.1101, 0.8045, 0.5392, 0.1635, 0.9957],
        [0.9188, 0.5549, 0.8723, 0.7991, 0.5664, 0.1828, 0.0813],
        [0.0460, 0.2289, 0.9059, 0.5317, 0.4941, 0.1949, 0.9953],
        [0.5152, 0.8023, 0.3776, 0.5205, 0.7639, 0.5859, 0.2331],
        [0.7067, 0.6229, 0.8419, 0.8239, 0.8090, 0.8861, 0.5153],
        [0.2647, 0.5367, 0.3675, 0.4064, 0.2526, 0.6533, 0.8317]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [ ]:
# Create another random tensor

# Perform matrix multiplication
random_tensor_B = torch.rand(1, 7)
matrix_mul = torch.matmul(random_tensor_A, random_tensor_B.T)
print(f"random_tensor_B: {random_tensor_B}")
(matrix_mul, matrix_mul.shape)

random_tensor_B: tensor([[0.0519, 0.3222, 0.3438, 0.7788, 0.4367, 0.2245, 0.6559]])


(tensor([[1.5615],
         [1.7133],
         [1.4903],
         [1.7139],
         [1.4383],
         [2.0586],
         [1.4320]]),
 torch.Size([7, 1]))

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [ ]:
# Set manual seed
RANDOM_SEED = 0
torch.manual_seed(seed=RANDOM_SEED)

# Create two random tensors
random_tensor_C = torch.rand(7, 7)
random_tensor_D = torch.rand(1, 7)


# Matrix multiply tensors
matrix_mul_2 = torch.matmul(random_tensor_C, random_tensor_D.T)
(matrix_mul_2, matrix_mul_2.shape)

(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]),
 torch.Size([7, 1]))

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [ ]:
# Set random seed on the GPU
torch.cuda.manual_seed(seed=1234)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [ ]:
# Set random seed
torch.manual_seed(seed=1234)

# Check for access to GPU
device = "cuda" if torch.cuda.is_available() else "cpu"
# Create two random tensors on GPU
random_tensor_E = torch.rand((2, 3), device=device)
random_tensor_F = torch.rand((2, 3), device=device)
print(f"Device: {device}")
(random_tensor_E, random_tensor_F)

Device: cuda


(tensor([[0.1272, 0.8167, 0.5440],
         [0.6601, 0.2721, 0.9737]], device='cuda:0'),
 tensor([[0.6208, 0.0276, 0.3255],
         [0.1114, 0.6812, 0.3608]], device='cuda:0'))


### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [ ]:
# Perform matmul on tensor_A and tensor_B
matrix_mul_3 = torch.matmul(random_tensor_E, random_tensor_F.T)
matrix_mul_3

tensor([[0.2786, 0.7668],
        [0.7343, 0.6102]], device='cuda:0')

### 8. Find the maximum and minimum values of the output of 7.

In [ ]:
# Find max
max_element_1 = matrix_mul_3.max()
max_element_2 = torch.max(matrix_mul_3)
print(max_element_1, max_element_2)
# Find min
min_element_1 = matrix_mul_3.min()
min_element_2 = torch.min(matrix_mul_3)
print(min_element_1, min_element_2)

tensor(0.7668, device='cuda:0') tensor(0.7668, device='cuda:0')
tensor(0.2786, device='cuda:0') tensor(0.2786, device='cuda:0')


### 9. Find the maximum and minimum index values of the output of 7.

In [ ]:
# Find arg max
argmax = matrix_mul_3.argmax()
print(f"Argmax: {argmax}")
# Find arg min
argmin = matrix_mul_3.argmin()
print(f"Argmin: {argmin}")

Argmax: 1
Argmin: 0



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [ ]:
# Set seed
torch.manual_seed(seed=7)

# Create random tensor
random_tensor_G = torch.rand((1, 1, 1, 10))

# Remove single dimensions
random_tensor_G_squeezed = random_tensor_G.squeeze()

# Print out tensors and their shapes
print(f"random_tensor_G: {(random_tensor_G, random_tensor_G.shape)}")
print(f"random_tensor_G_squeezed: {(random_tensor_G_squeezed, random_tensor_G_squeezed.shape)}")

random_tensor_G: (tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]), torch.Size([1, 1, 1, 10]))
random_tensor_G_squeezed: (tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]), torch.Size([10]))
